// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtbceoemzdauoiytxwzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0YmNlb2VtemRhdW9peXR4d3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzgwMjAsImV4cCI6MjA2NTQ1NDAyMH0.Q6kf_QedaqRsByCi8D324OFXiV85vWv2INL5ufJ5dCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);